= Components Sample :: Beam :: Kafka

== Runtime

=== Apache Beam

Beam facet generates component tests using Apache Beam testing framework. It executes the tests using a real beam pipeline to go through the runtime constraints of Apache Beam which can be more strict than Talend Component Kit ones.

==== Files generated by this facet

- src/test/java/org/talend/component/beam/kafka/source/KafkaInputMapperBeamTest.java
- src/test/java/org/talend/component/beam/kafka/source/CompanyComponent3MapperBeamTest.java
- src/test/java/org/talend/component/beam/kafka/source/CompanyComponent4MapperBeamTest.java
- src/test/java/org/talend/component/beam/kafka/processor/FilterRowProcessorBeamTest.java


== Test

=== Talend Component Kit Testing

Talend Component Kit Testing skeleton generator. For each component selected it generates an associated test suffixed with `Test`.

==== Files generated by this facet

- src/test/java/org/talend/component/beam/kafka/source/KafkaInputMapperTest.java
- src/test/java/org/talend/component/beam/kafka/source/CompanyComponent3MapperTest.java
- src/test/java/org/talend/component/beam/kafka/source/CompanyComponent4MapperTest.java
- src/test/java/org/talend/component/beam/kafka/processor/FilterRowProcessorTest.java


== Tool

=== Codenvy

Codenvy allows you to code on this project from any web browser if you host your sources in a Github repository.

Click on this link and the project will be opened on your account, ready to develop:

image:http://beta.codenvy.com/factory/resources/codenvy-contribute.svg[Codenvy,link=http://codenvy.io/f?url=https://github.com/FriendlyMcNicerson/component-beam-kafka,window="_blank"]

==== Files generated by this facet

- .codenvy.json

